title: "Computational Tools for Data Science"
author: "Mark Crovella"
logo: figs/L09-MultivariateNormal.png
only_build_toc_files: true
copyright: '2021-2022'
repository:
        url: https://github.com/mcrovella/CS506-Computational-Tools-for-Data-Science
html:
        # favicon: images/DiagramAR-icon.png
        use_repository_button: true
execute:
  execute_notebooks: "cache"
  # I occasionally have cells that demonstrate python errors -- keep going!
  allow_errors: true
  timeout: 100
parse:
  # see https://jupyterbook.org/customize/config.html
  # first one is the only one I added to the set of defaults
  myst_enable_extensions:
    - html_image
    - amsmath
    - colon_fence
    - dollarmath
    - linkify
    - substitution
sphinx:
  config:
    mathjax_path: https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
